name: TestBuildEpl

on:
#    workflow_dispatch:
    [workflow_dispatch,push]

permissions:
  contents: read
  
jobs:
    test_build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Install EPL
              run: git clone https://github.com/WmFreeSmile/elbuild.git
            - name: Show dir
              run: dir .\elbuild
            - name: Make test.e
              run: .\elbuild\eplc.exe test.e /o test.exe /static /set_epl_root .\elbuild\
            - name: Show result
              run: dir
              
            - name: upload result
              uses: actions/upload-artifact@v4
              with:
                name: test
                path: ${{ github.workspace }}\test.exe
                